// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Hafizh",
            "email": "hafizh@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/dashboard/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan jumlah total akun, akun aktif (90 hari), inaktif, dan antrean device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "4. Admin - Dashboard \u0026 Device"
                ],
                "summary": "Statistik Dashboard Admin",
                "responses": {
                    "200": {
                        "description": "Data Statistik",
                        "schema": {
                            "$ref": "#/definitions/controllers.AdminStatsResponse"
                        }
                    }
                }
            }
        },
        "/admin/device/reject": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menolak akses login dari HP yang tidak dikenal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "4. Admin - Dashboard \u0026 Device"
                ],
                "summary": "Tolak Perangkat Siswa",
                "parameters": [
                    {
                        "description": "ID Perangkat",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.DeviceActionReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Perangkat Ditolak",
                        "schema": {
                            "$ref": "#/definitions/controllers.SuccessMessage"
                        }
                    }
                }
            }
        },
        "/admin/kelas/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "5. Admin - Master Data"
                ],
                "summary": "Tambah Kelas Baru",
                "parameters": [
                    {
                        "description": "Nama Kelas",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateKelasReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Kelas berhasil ditambahkan",
                        "schema": {
                            "$ref": "#/definitions/controllers.SuccessMessage"
                        }
                    }
                }
            }
        },
        "/admin/mapel/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "5. Admin - Master Data"
                ],
                "summary": "Tambah Mata Pelajaran Baru",
                "parameters": [
                    {
                        "description": "Nama Mapel",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.CreateMapelReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mapel berhasil ditambahkan",
                        "schema": {
                            "$ref": "#/definitions/controllers.SuccessMessage"
                        }
                    }
                }
            }
        },
        "/admin/siswa/all": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengambil daftar seluruh data master siswa",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "5. Admin - Master Data"
                ],
                "summary": "Tampilkan Semua Data Siswa",
                "responses": {
                    "200": {
                        "description": "Data Siswa",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.SiswaData"
                            }
                        }
                    }
                }
            }
        },
        "/admin/siswa/reset-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Admin mereset password siswa dengan validasi Kata Kunci Rahasia",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "4. Admin - Device \u0026 Keamanan"
                ],
                "summary": "Reset Password Siswa (Lupa Password)",
                "parameters": [
                    {
                        "description": "Data Reset",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ResetPassSiswaReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password berhasil direset",
                        "schema": {
                            "$ref": "#/definitions/controllers.SuccessMessage"
                        }
                    }
                }
            }
        },
        "/guru/backup": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Melakukan dump SQL dan mengunggahnya otomatis ke folder Drive",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "3. Operasional Guru"
                ],
                "summary": "Backup Database ke Google Drive",
                "responses": {
                    "200": {
                        "description": "Backup Berhasil Diupload",
                        "schema": {
                            "$ref": "#/definitions/controllers.SuccessMessage"
                        }
                    }
                }
            }
        },
        "/guru/dashboard/attendance-list": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan daftar nama siswa dan status absensinya (Hadir/Belum)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "3. Operasional Guru"
                ],
                "summary": "Detail Status Kehadiran Per Siswa",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Sesi Pembelajaran",
                        "name": "sesi_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Daftar Kehadiran",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.StudentStatusList"
                            }
                        }
                    }
                }
            }
        },
        "/guru/dashboard/stats": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan total murid terdaftar, hadir, dan rasio kehadiran",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "3. Operasional Guru"
                ],
                "summary": "Ringkasan Statistik Kelas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Sesi Pembelajaran",
                        "name": "sesi_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Data Ditemukan",
                        "schema": {
                            "$ref": "#/definitions/controllers.GuruStatsResponse"
                        }
                    }
                }
            }
        },
        "/guru/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Otomatis mengunduh file Excel laporan absensi dan mem-backup ke G-Drive",
                "produces": [
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "3. Operasional Guru"
                ],
                "summary": "Download Laporan Excel",
                "responses": {
                    "200": {
                        "description": "File Downloaded",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/guru/generate-qr": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menghasilkan JWT token beralaku 30 detik untuk diubah jadi gambar QR",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "3. Operasional Guru"
                ],
                "summary": "Tampilkan QR Code (Guru)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID Sesi Pembelajaran",
                        "name": "sesi_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Sukses Membuat QR",
                        "schema": {
                            "$ref": "#/definitions/controllers.GuruQRResponse"
                        }
                    }
                }
            }
        },
        "/guru/jadwal": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan sesi pembelajaran berdasarkan guru yang sedang login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "3. Operasional Guru"
                ],
                "summary": "Jadwal Mengajar Guru",
                "responses": {
                    "200": {
                        "description": "Daftar Jadwal",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.JadwalGuru"
                            }
                        }
                    }
                }
            }
        },
        "/guru/reset-password": {
            "post": {
                "description": "Mengganti kata sandi guru menggunakan token rahasia",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "1. Auth \u0026 Keamanan"
                ],
                "summary": "Eksekusi Reset Password",
                "parameters": [
                    {
                        "description": "Token dan Password Baru",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.ResetPasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password berhasil diubah",
                        "schema": {
                            "$ref": "#/definitions/controllers.SuccessMessage"
                        }
                    }
                }
            }
        },
        "/guru/restore": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengunduh file SQL dari Drive menggunakan File ID dan menimpanya ke database lokal",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "3. Operasional Guru"
                ],
                "summary": "Restore Database dari Google Drive",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Google Drive File ID",
                        "name": "file_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Database Berhasil Direstore",
                        "schema": {
                            "$ref": "#/definitions/controllers.SuccessMessage"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Autentikasi untuk Admin dan Guru mengembalikan token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "1. Auth \u0026 Keamanan"
                ],
                "summary": "Login Admin \u0026 Guru",
                "parameters": [
                    {
                        "description": "Kredensial Login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil Login",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginSiswaResponse"
                        }
                    }
                }
            }
        },
        "/login/siswa": {
            "post": {
                "description": "Autentikasi siswa dan mendaftarkan ID perangkat (Device Binding)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "1. Auth \u0026 Keamanan"
                ],
                "summary": "Login untuk Siswa",
                "parameters": [
                    {
                        "description": "Payload Data Login",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginSiswaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil Login",
                        "schema": {
                            "$ref": "#/definitions/controllers.LoginSiswaResponse"
                        }
                    },
                    "401": {
                        "description": "Kredensial Salah",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/siswa/absen/submit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Mengirim token QR dinamis dan koordinat GPS Siswa untuk divalidasi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "2. Operasional Siswa"
                ],
                "summary": "Submit Absensi Geofencing (Siswa)",
                "parameters": [
                    {
                        "description": "Kirim Koordinat dan Token",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.AbsenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Posisi tervalidasi, Absen Sukses",
                        "schema": {
                            "$ref": "#/definitions/controllers.SuccessMessage"
                        }
                    },
                    "403": {
                        "description": "Di luar jangkauan radius / QR Kadaluwarsa",
                        "schema": {
                            "$ref": "#/definitions/controllers.ErrorMessage"
                        }
                    }
                }
            }
        },
        "/siswa/riwayat": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Menampilkan data historis absensi milik siswa yang sedang login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "2. Operasional Siswa"
                ],
                "summary": "Riwayat Absensi Siswa",
                "responses": {
                    "200": {
                        "description": "Daftar Riwayat",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/controllers.RiwayatAbsenSiswa"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.AbsenRequest": {
            "type": "object",
            "properties": {
                "latitude": {
                    "type": "number",
                    "example": -7.250446
                },
                "longitude": {
                    "type": "number",
                    "example": 112.768846
                },
                "qr_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                },
                "sesi_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.AdminStatsResponse": {
            "type": "object",
            "properties": {
                "akun_aktif": {
                    "type": "integer",
                    "example": 142
                },
                "akun_inaktif": {
                    "type": "integer",
                    "example": 8
                },
                "pending_device": {
                    "type": "integer",
                    "example": 3
                },
                "total_akun": {
                    "type": "integer",
                    "example": 150
                }
            }
        },
        "controllers.CreateKelasReq": {
            "type": "object",
            "properties": {
                "nama_kelas": {
                    "type": "string",
                    "example": "XII RPL 1"
                }
            }
        },
        "controllers.CreateMapelReq": {
            "type": "object",
            "properties": {
                "nama_mapel": {
                    "type": "string",
                    "example": "Pemrograman Web \u0026 Perangkat Bergerak"
                }
            }
        },
        "controllers.DeviceActionReq": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "controllers.ErrorMessage": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Terjadi kesalahan: data tidak valid"
                }
            }
        },
        "controllers.GuruQRResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "QR Code berhasil dibuat, berlaku 30 detik!"
                },
                "qr_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6..."
                }
            }
        },
        "controllers.GuruStatsResponse": {
            "type": "object",
            "properties": {
                "absent_today": {
                    "type": "integer",
                    "example": 2
                },
                "attendance_rate": {
                    "type": "number",
                    "example": 93.33
                },
                "present_today": {
                    "type": "integer",
                    "example": 28
                },
                "total_students": {
                    "type": "integer",
                    "example": 30
                }
            }
        },
        "controllers.JadwalGuru": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "kelas": {
                    "type": "string",
                    "example": "XII RPL 1"
                },
                "mata_pelajaran": {
                    "type": "string",
                    "example": "Pemrograman Web"
                },
                "waktu_mulai": {
                    "type": "string",
                    "example": "08:00"
                },
                "waktu_selesai": {
                    "type": "string",
                    "example": "10:00"
                }
            }
        },
        "controllers.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string",
                    "example": "rahasia123"
                },
                "username": {
                    "type": "string",
                    "example": "admin_utama"
                }
            }
        },
        "controllers.LoginSiswaRequest": {
            "type": "object",
            "properties": {
                "device_token": {
                    "type": "string",
                    "example": "hp-hafizh-xyz-123"
                },
                "password": {
                    "type": "string",
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "siswa01"
                }
            }
        },
        "controllers.LoginSiswaResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "properties": {
                        "role": {
                            "type": "string",
                            "example": "siswa"
                        },
                        "token": {
                            "type": "string",
                            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp..."
                        }
                    }
                },
                "message": {
                    "type": "string",
                    "example": "Login berhasil!"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "controllers.ResetPassSiswaReq": {
            "type": "object",
            "properties": {
                "kata_kunci": {
                    "type": "string",
                    "example": "KucingKu"
                },
                "new_password": {
                    "type": "string",
                    "example": "SandiBaru123"
                },
                "nis": {
                    "type": "string",
                    "example": "22010101"
                }
            }
        },
        "controllers.ResetPasswordReq": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string",
                    "example": "PasswordBaru123!"
                },
                "token": {
                    "type": "string",
                    "example": "817cdc18e67140e57f62dd6c80fd52529..."
                }
            }
        },
        "controllers.RiwayatAbsenSiswa": {
            "type": "object",
            "properties": {
                "mapel": {
                    "type": "string",
                    "example": "Matematika"
                },
                "status": {
                    "type": "string",
                    "example": "hadir"
                },
                "tanggal": {
                    "type": "string",
                    "example": "2026-04-08"
                }
            }
        },
        "controllers.SiswaData": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "hafizh@example.com"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "nama_lengkap": {
                    "type": "string",
                    "example": "Hafizh Junior"
                },
                "nis": {
                    "type": "string",
                    "example": "22010101"
                }
            }
        },
        "controllers.StudentStatusList": {
            "type": "object",
            "properties": {
                "nama": {
                    "type": "string",
                    "example": "Hafizh Junior"
                },
                "nis": {
                    "type": "string",
                    "example": "22010101"
                },
                "status": {
                    "type": "string",
                    "example": "hadir"
                },
                "waktu_absen": {
                    "type": "string",
                    "example": "2026-04-08 09:15:00"
                }
            }
        },
        "controllers.SuccessMessage": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Aksi berhasil dilakukan!"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Masukkan token JWT dengan format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API Sistem Absensi Tempat Les",
	Description:      "Ini adalah dokumentasi REST API untuk aplikasi absensi dengan fitur QR & Geofencing.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
